micronaut.application.name=test_app
datasources.default.url=jdbc:sqlite:${DB_PATH:data.db}
datasources.default.schema-generate=CREATE
datasources.default.dialect=H2
datasources.default.db-type=sqlite
datasources.default.maximum-pool-size=2
datasources.default.minimum-idle=2
datasources.default.idle-timeout=30000